// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl8NIEfhQ_27qa7gjWHSEmnjjzVpwM2NE',
    appId: '1:400336991808:web:611a93c5996716398551a5',
    messagingSenderId: '400336991808',
    projectId: 'fitness-challenge-yousef-ed8d7',
    authDomain: 'fitness-challenge-yousef-ed8d7.firebaseapp.com',
    storageBucket: 'fitness-challenge-yousef-ed8d7.firebasestorage.app',
    measurementId: 'G-5Y8ZXJVDNX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSvbieSchL4dWAtGATj_XOrPx_bm0AWVM',
    appId: '1:400336991808:android:e97f779c56c20d978551a5',
    messagingSenderId: '400336991808',
    projectId: 'fitness-challenge-yousef-ed8d7',
    storageBucket: 'fitness-challenge-yousef-ed8d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY2JzRfD6dpmKME6BCn7j0m4jY7QyRJ5Y',
    appId: '1:400336991808:ios:2353ebb432c390818551a5',
    messagingSenderId: '400336991808',
    projectId: 'fitness-challenge-yousef-ed8d7',
    storageBucket: 'fitness-challenge-yousef-ed8d7.firebasestorage.app',
    iosBundleId: 'com.example.fitnessChallenge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY2JzRfD6dpmKME6BCn7j0m4jY7QyRJ5Y',
    appId: '1:400336991808:ios:2353ebb432c390818551a5',
    messagingSenderId: '400336991808',
    projectId: 'fitness-challenge-yousef-ed8d7',
    storageBucket: 'fitness-challenge-yousef-ed8d7.firebasestorage.app',
    iosBundleId: 'com.example.fitnessChallenge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAl8NIEfhQ_27qa7gjWHSEmnjjzVpwM2NE',
    appId: '1:400336991808:web:13ded4d0d1dfd1378551a5',
    messagingSenderId: '400336991808',
    projectId: 'fitness-challenge-yousef-ed8d7',
    authDomain: 'fitness-challenge-yousef-ed8d7.firebaseapp.com',
    storageBucket: 'fitness-challenge-yousef-ed8d7.firebasestorage.app',
    measurementId: 'G-ELW8MK7LM5',
  );

}